name: Lint Commit Messages
on: [pull_request_target]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PIPELINE_BOT_PAT }}
          fetch-depth: 0
      - name: Ensure full history
        run: |
          git remote add upstream ${{ github.event.pull_request.head.repo.ssh_url }}
          git fetch
      - id: commitlint
        uses: wagoid/commitlint-github-action@v5
      - id: lint_results_msg
        name: Generate Lint Results Message
        if: always()
        run: |
          npm i commander
          npm i @actions/core
          node ./workflow-helpers/generate-commitlint-response.js --results '${{ steps.commitlint.outputs.results }}'
      - name: Post comment
        if: ${{ always() }}
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
          message: |
            ## Commitlint

            ${{ steps.lint_results_msg.outputs.msg }}
